class CfgWLRequisitionPresets
{
	class A3ReduxAll // --- class name used in the Init module
	{
		class WEST // --- assets available for BLUFOR
		{
			class Infantry
			{
				class B_W_Soldier_A_F // Ammo Bearer 	BLUFOR 	NATO (Woodland) --- must be asset class name
				{
					cost = 150; // --- Command Points required
					requirements[] = {}; // --- dispositions required ("A" = airstrip, "H" = helipad, "W" = water (harbor))
				};
				class B_W_Soldier_AAR_F // Asst. Autorifleman 	BLUFOR 	NATO (Woodland) --- must be asset class name
				{
					cost = 150; // --- Command Points required
					requirements[] = {}; // --- dispositions required ("A" = airstrip, "H" = helipad, "W" = water (harbor))
				};
				class B_W_Soldier_AR_F // Autorifleman 	BLUFOR 	NATO (Woodland) --- must be asset class name
				{
					cost = 150; // --- Command Points required
					requirements[] = {}; // --- dispositions required ("A" = airstrip, "H" = helipad, "W" = water (harbor))
				};
				class B_W_Medic_F // Combat Life Saver 	BLUFOR 	NATO (Woodland) --- must be asset class name
				{
					cost = 125; // --- Command Points required
					requirements[] = {}; // --- dispositions required ("A" = airstrip, "H" = helipad, "W" = water (harbor))
				};
				class B_W_Crew_F // Crewman 	BLUFOR 	NATO (Woodland) --- must be asset class name
				{
					cost = 100; // --- Command Points required
					requirements[] = {}; // --- dispositions required ("A" = airstrip, "H" = helipad, "W" = water (harbor))
				};
				class B_W_Engineer_F // Engineer 	BLUFOR 	NATO (Woodland) --- must be asset class name
				{
					cost = 200; // --- Command Points required
					requirements[] = {}; // --- dispositions required ("A" = airstrip, "H" = helipad, "W" = water (harbor))
				};
				class B_W_Soldier_Exp_F // Explosive Specialist 	BLUFOR 	NATO (Woodland) --- must be asset class name
				{
					cost = 200; // --- Command Points required
					requirements[] = {}; // --- dispositions required ("A" = airstrip, "H" = helipad, "W" = water (harbor))
				};
				class B_W_soldier_mine_F // Mine Specialist 	BLUFOR 	NATO (Woodland) --- must be asset class name
				{
					cost = 200; // --- Command Points required
					requirements[] = {}; // --- dispositions required ("A" = airstrip, "H" = helipad, "W" = water (harbor))
				};
				class B_W_Soldier_GL_F // Grenadier 	BLUFOR 	NATO (Woodland) --- must be asset class name
				{
					cost = 125; // --- Command Points required
					requirements[] = {}; // --- dispositions required ("A" = airstrip, "H" = helipad, "W" = water (harbor))
				};
				class B_W_Helipilot_F // Helicopter Pilot 	BLUFOR 	NATO (Woodland) --- must be asset class name
				{
					cost = 100; // --- Command Points required
					requirements[] = {}; // --- dispositions required ("A" = airstrip, "H" = helipad, "W" = water (harbor))
				};
				class B_W_soldier_M_F // Marksman 	BLUFOR 	NATO (Woodland) --- must be asset class name
				{
					cost = 150; // --- Command Points required
					requirements[] = {}; // --- dispositions required ("A" = airstrip, "H" = helipad, "W" = water (harbor))
				};
				class B_W_Soldier_AA_F // Missile Specialist (AA) 	BLUFOR 	NATO (Woodland)--- must be asset class name
				{
					cost = 300; // --- Command Points required
					requirements[] = {}; // --- dispositions required ("A" = airstrip, "H" = helipad, "W" = water (harbor))
				};
				class B_W_Soldier_AT_F // Missile Specialist (AT) 	BLUFOR 	NATO (Woodland) --- must be asset class name
				{
					cost = 300; // --- Command Points required
					requirements[] = {}; // --- dispositions required ("A" = airstrip, "H" = helipad, "W" = water (harbor))
				};
				class B_W_Soldier_Repair_F // Repair Specialist 	BLUFOR 	NATO (Woodland) --- must be asset class name
				{
					cost = 200; // --- Command Points required
					requirements[] = {}; // --- dispositions required ("A" = airstrip, "H" = helipad, "W" = water (harbor))
				};
				class B_W_Soldier_F // Rifleman 	BLUFOR 	NATO (Woodland) --- must be asset class name
				{
					cost = 100; // --- Command Points required
					requirements[] = {}; // --- dispositions required ("A" = airstrip, "H" = helipad, "W" = water (harbor))
				};
				class B_CTRG_Soldier_Medic_tna_F // Paramedic 	BLUFOR 	CTRG --- must be asset class name
				{
					cost = 1000; // --- Command Points required
					requirements[] = {}; // --- dispositions required ("A" = airstrip, "H" = helipad, "W" = water (harbor))
				};
				class B_CTRG_Soldier_M_tna_F // Marksman 	BLUFOR 	CTRG --- must be asset class name
				{
					cost = 1000; // --- Command Points required
					requirements[] = {}; // --- dispositions required ("A" = airstrip, "H" = helipad, "W" = water (harbor))
				};
				class B_CTRG_Soldier_tna_F // Scout 	BLUFOR 	CTRG --- must be asset class name
				{
					cost = 1000; // --- Command Points required
					requirements[] = {}; // --- dispositions required ("A" = airstrip, "H" = helipad, "W" = water (harbor))
				};
				class B_CTRG_Soldier_LAT_tna_F // Scout (AT) 	BLUFOR 	CTRG --- must be asset class name
				{
					cost = 1100; // --- Command Points required
					requirements[] = {}; // --- dispositions required ("A" = airstrip, "H" = helipad, "W" = water (harbor))
				};
				class B_CTRG_Soldier_AR_tna_F // Autorifleman 	BLUFOR 	CTRG --- must be asset class name
				{
					cost = 1000; // --- Command Points required
					requirements[] = {}; // --- dispositions required ("A" = airstrip, "H" = helipad, "W" = water (harbor))
				};
				class B_CTRG_Soldier_JTAC_tna_F // JTAC 	BLUFOR 	CTRG --- must be asset class name
				{
					cost = 1000; // --- Command Points required
					requirements[] = {}; // --- dispositions required ("A" = airstrip, "H" = helipad, "W" = water (harbor))
				};
			};
			class Vehicles
			{
				class B_Quadbike_01_F // Quad Bike 	BLUFOR 	NATO 
				{
					cost = 100;
					requirements[] = {};
				};
				class B_LSV_01_unarmed_black_F // Prowler (Unarmed) 	BLUFOR 	NATO 
				{
					cost = 350;
					requirements[] = {};
				};
				class B_LSV_01_armed_black_F // Prowler (HMG) 	BLUFOR 	NATO (Pacific)
				{
					cost = 1000;
					requirements[] = {};
				};
				class B_T_MRAP_01_F // Hunter 	BLUFOR 	NATO (Pacific) 
				{
					cost = 500;
					requirements[] = {};
				};
				class B_T_MRAP_01_gmg_F // Hunter GMG 	BLUFOR 	NATO (Pacific)
				{
					cost = 1600;
					requirements[] = {};
				};
				class B_T_MRAP_01_hmg_F // Hunter HMG 	BLUFOR 	NATO (Pacific)
				{
					cost = 1400;
					requirements[] = {};
				};
				class B_T_Truck_01_transport_F // HEMTT Transport 	BLUFOR 	NATO (Pacific) 
				{
					cost = 200;
					requirements[] = {};
				};
				class B_T_Truck_01_covered_F // HEMTT Transport (Covered) 	BLUFOR 	NATO (Pacific)
				{
					cost = 250;
					requirements[] = {};
				};
				class B_T_APC_Wheeled_01_cannon_F // AMV-7 Marshall 	BLUFOR 	NATO (Pacific)
				{
					cost = 3000;
					requirements[] = {};
				};
				class B_G_Offroad_01_repair_F // Offroad (Repair) 	BLUFOR 	FIA 
				{
					cost = 500;
					requirements[] = {};
				};
				class B_G_Van_01_fuel_F // Fuel Truck 	BLUFOR 	FIA 
				{
					cost = 750;
					requirements[] = {};
				};
				class B_G_Van_02_transport_F // Van Transport 	BLUFOR 	FIA 
				{
					cost = 200;
					requirements[] = {};
				};
				class B_UGV_02_Demining_F // ED-1D Pelter 	BLUFOR 	NATO 
				{
					cost = 750;
					requirements[] = {};
				};
				class B_T_UGV_01_rcws_olive_F // UGV Stomper RCWS 	BLUFOR 	NATO (Pacific) 
				{
					cost = 1000;
					requirements[] = {};
				};
			};
			class Aircraft
			{
				class B_UAV_01_F // AR-2 Darter 	BLUFOR 	NATO 
				{
					cost = 500;
					requirements[] = {};
				};
				class B_Heli_Light_01_F // MH-9 Hummingbird 	BLUFOR 	NATO 
				{
					cost = 750;
					requirements[] = {H};
				};
			};
			class Naval
			{
				class B_T_Boat_Transport_01_F // Assault Boat 	BLUFOR 	NATO (Pacific)
				{
					cost = 100;
					requirements[] = { "W" };
				};
			};
			class Gear
			{
				class Box_NATO_Wps_F // Basic Weapons [NATO] 	Civilian 	Supplies
				{ 
					cost = 250;
					requirements[] = {};
				};
				class Box_NATO_WpsSpecial_F // Special Weapons [NATO] 	Civilian 	Supplies 
				{
					cost = 500;
					requirements[] = {};
				};
				class Box_NATO_Ammo_F // Basic Ammo [NATO] 	Civilian 	Supplies 
				{
					cost = 200;
					requirements[] = {};
				};
				class Box_NATO_AmmoOrd_F // Explosives [NATO] 	Civilian 	Supplies 
				{
					cost = 250;
					requirements[] = {};
				};
				class Box_NATO_Grenades_F // Grenades [NATO] 	Civilian 	Supplies 
				{
					cost = 200;
					requirements[] = {};
				};
				class Box_NATO_Support_F // Support [NATO] 	Civilian 	Supplies 
				{
					cost = 250;
					requirements[] = {};
				};
				class Box_NATO_WpsLaunch_F // Launchers [NATO] 	Civilian 	Supplies 
				{
					cost = 300;
					requirements[] = {};
				};
				class Box_NATO_AmmoVeh_F // Vehicle Ammo [NATO] 	Civilian 	Supplies
				{
					cost = 540;
					requirements[] = {};
				};
				class C_supplyCrate_F // Supply Box [CTRG] 	Civilian 	Supplies
				{
					cost = 200;
					requirements[] = {};
				};
				class Land_RepairDepot_01_green_F // Repair depot (Green) 	Civilian 	Supplies 
				{
					cost = 1000;
					requirements[] = {};
				};
				
			};
			class Defences
			{
				class B_HMG_01_F // Mk30 HMG .50 	BLUFOR 	NATO 
				{
					cost = 250;
					requirements[] = {};
					offset[] = { 0, 5.3, 0 }; // --- custom offset (optional)
				};
				class B_HMG_01_high_F // Mk30 HMG .50 (Raised) 	BLUFOR 	NATO 
				{
					cost = 250;
					requirements[] = {};
					offset[] = { 0, 5.3, 0 }; // --- custom offset (optional)
				};
				class B_HMG_01_A_F // Mk30A HMG .50 	BLUFOR 	NATO 
				{
					cost = 500;
					requirements[] = {};
					offset[] = { 0, 5.3, 0 }; // --- custom offset (optional)
				};
				class B_GMG_01_F // Mk32 GMG 20 mm 	BLUFOR 	NATO 
				{
					cost = 250;
					requirements[] = {};
					offset[] = { 0, 5.3, 0 }; // --- custom offset (optional)
				};
				class B_GMG_01_high_F // Mk32 GMG 20 mm (Raised) 	BLUFOR 	NATO
				{
					cost = 250;
					requirements[] = {};
					offset[] = { 0, 5.3, 0 }; // --- custom offset (optional)
				};
				class B_GMG_01_A_F // Mk32A GMG 20 mm 	BLUFOR 	NATO 
				{
					cost = 500;
					requirements[] = {};
					offset[] = { 0, 5.3, 0 }; // --- custom offset (optional)
				};
				class B_static_AA_F // Static Titan Launcher (AA) [NATO] 	BLUFOR 	NATO 
				{
					cost = 500;
					requirements[] = {};
					offset[] = { 0, 5.3, 0 }; // --- custom offset (optional)
				};
				class B_static_AT_F // Static Titan Launcher (AT) [NATO] 	BLUFOR 	NATO 
				{
					cost = 500;
					requirements[] = {};
					offset[] = { 0, 5.3, 0 }; // --- custom offset (optional)
				};
			};
		};
		class EAST // --- assets available for OPFOR
		{
			class Infantry
			{
				class O_T_Soldier_A_F // Ammo Bearer 	OPFOR 	CSAT (Pacific)  --- must be asset class name
				{
					cost = 150; // --- Command Points required
					requirements[] = {}; // --- dispositions required ("A" = airstrip, "H" = helipad, "W" = water (harbor))
				};
				class O_T_Soldier_AAR_F // Asst. Autorifleman 	OPFOR 	CSAT (Pacific)  --- must be asset class name
				{
					cost = 150; // --- Command Points required
					requirements[] = {}; // --- dispositions required ("A" = airstrip, "H" = helipad, "W" = water (harbor))
				};
				class O_T_Soldier_AR_F // Autorifleman 	OPFOR 	CSAT (Pacific) --- must be asset class name
				{
					cost = 150; // --- Command Points required
					requirements[] = {}; // --- dispositions required ("A" = airstrip, "H" = helipad, "W" = water (harbor))
				};
				class O_T_Medic_F // Combat Life Saver 	OPFOR 	CSAT (Pacific)  --- must be asset class name
				{
					cost = 125; // --- Command Points required
					requirements[] = {}; // --- dispositions required ("A" = airstrip, "H" = helipad, "W" = water (harbor))
				};
				class O_T_Crew_F // Crewman 	OPFOR 	CSAT (Pacific) --- must be asset class name
				{
					cost = 100; // --- Command Points required
					requirements[] = {}; // --- dispositions required ("A" = airstrip, "H" = helipad, "W" = water (harbor))
				};
				class O_T_Engineer_F // Engineer 	OPFOR 	CSAT (Pacific) --- must be asset class name
				{
					cost = 200; // --- Command Points required
					requirements[] = {}; // --- dispositions required ("A" = airstrip, "H" = helipad, "W" = water (harbor))
				};
				class O_T_Soldier_Exp_F // Explosive Specialist 	OPFOR 	CSAT (Pacific) --- must be asset class name
				{
					cost = 200; // --- Command Points required
					requirements[] = {}; // --- dispositions required ("A" = airstrip, "H" = helipad, "W" = water (harbor))
				};
				class O_T_soldier_mine_F // Mine Specialist 	OPFOR 	CSAT (Pacific) --- must be asset class name
				{
					cost = 200; // --- Command Points required
					requirements[] = {}; // --- dispositions required ("A" = airstrip, "H" = helipad, "W" = water (harbor))
				};
				class O_T_Soldier_GL_F // Grenadier 	OPFOR 	CSAT (Pacific)  --- must be asset class name
				{
					cost = 125; // --- Command Points required
					requirements[] = {}; // --- dispositions required ("A" = airstrip, "H" = helipad, "W" = water (harbor))
				};
				class O_T_Helipilot_F // Helicopter Pilot 	OPFOR 	CSAT (Pacific)  --- must be asset class name
				{
					cost = 100; // --- Command Points required
					requirements[] = {}; // --- dispositions required ("A" = airstrip, "H" = helipad, "W" = water (harbor))
				};
				class O_T_Soldier_M_F // Marksman 	OPFOR 	CSAT (Pacific)  --- must be asset class name
				{
					cost = 150; // --- Command Points required
					requirements[] = {}; // --- dispositions required ("A" = airstrip, "H" = helipad, "W" = water (harbor))
				};
				class O_T_Soldier_AA_F // Missile Specialist (AA) 	OPFOR 	CSAT (Pacific) --- must be asset class name
				{
					cost = 300; // --- Command Points required
					requirements[] = {}; // --- dispositions required ("A" = airstrip, "H" = helipad, "W" = water (harbor))
				};
				class O_T_Soldier_AT_F // Missile Specialist (AT) 	OPFOR 	CSAT (Pacific) 	 --- must be asset class name
				{
					cost = 300; // --- Command Points required
					requirements[] = {}; // --- dispositions required ("A" = airstrip, "H" = helipad, "W" = water (harbor))
				};
				class O_T_Soldier_Repair_F // Repair Specialist 	OPFOR 	CSAT (Pacific)  --- must be asset class name
				{
					cost = 200; // --- Command Points required
					requirements[] = {}; // --- dispositions required ("A" = airstrip, "H" = helipad, "W" = water (harbor))
				};
				class O_T_Soldier_F // Rifleman 	OPFOR 	CSAT (Pacific)  --- must be asset class name
				{
					cost = 100; // --- Command Points required
					requirements[] = {}; // --- dispositions required ("A" = airstrip, "H" = helipad, "W" = water (harbor))
				};
				class O_V_Soldier_Medic_hex_F // Viper Paramedic 	OPFOR 	CSAT  --- must be asset class name
				{
					cost = 1000; // --- Command Points required
					requirements[] = {}; // --- dispositions required ("A" = airstrip, "H" = helipad, "W" = water (harbor))
				};
				class O_V_Soldier_M_hex_F // Viper Marksman 	OPFOR 	CSAT --- must be asset class name
				{
					cost = 1000; // --- Command Points required
					requirements[] = {}; // --- dispositions required ("A" = airstrip, "H" = helipad, "W" = water (harbor))
				};
				class O_V_Soldier_hex_F // Viper Operative 	OPFOR 	CSAT  --- must be asset class name
				{
					cost = 1000; // --- Command Points required
					requirements[] = {}; // --- dispositions required ("A" = airstrip, "H" = helipad, "W" = water (harbor))
				};
				class O_V_Soldier_LAT_hex_F // Viper Rifleman (AT) 	OPFOR 	CSAT  --- must be asset class name
				{
					cost = 1100; // --- Command Points required
					requirements[] = {}; // --- dispositions required ("A" = airstrip, "H" = helipad, "W" = water (harbor))
				};
				class O_V_Soldier_Exp_hex_F // Viper Demo Specialist 	OPFOR 	CSAT  --- must be asset class name
				{
					cost = 1000; // --- Command Points required
					requirements[] = {}; // --- dispositions required ("A" = airstrip, "H" = helipad, "W" = water (harbor))
				};
				class O_V_Soldier_JTAC_hex_F // Viper JTAC 	OPFOR 	CSAT  --- must be asset class name
				{
					cost = 1000; // --- Command Points required
					requirements[] = {}; // --- dispositions required ("A" = airstrip, "H" = helipad, "W" = water (harbor))
				};
			};
			class Vehicles
			{
				class O_T_Quadbike_01_ghex_F // Quad Bike 	OPFOR 	CSAT (Pacific)  
				{
					cost = 100;
					requirements[] = {};
				};
				class O_LSV_02_unarmed_F // Qilin (Unarmed) 	OPFOR 	CSAT 
				{
					cost = 350;
					requirements[] = {};
				};
				class O_LSV_02_armed_viper_F // Qilin (Minigun) 	OPFOR 	CSAT 
				{
					cost = 1000;
					requirements[] = {};
				};
				class O_T_MRAP_02_ghex_F //  	Ifrit 	OPFOR 	CSAT (Pacific) 
				{
					cost = 500;
					requirements[] = {};
				};
				class O_T_MRAP_02_gmg_ghex_F // Ifrit GMG 	OPFOR 	CSAT (Pacific) 	
				{
					cost = 1600;
					requirements[] = {};
				};
				class O_T_MRAP_02_hmg_ghex_F // Ifrit HMG 	OPFOR 	CSAT (Pacific) 
				{
					cost = 1400;
					requirements[] = {};
				};
				class O_T_Truck_03_transport_ghex_F // Tempest Transport 	OPFOR 	CSAT (Pacific) 
				{
					cost = 200;
					requirements[] = {};
				};
				class O_T_Truck_03_covered_ghex_F // Tempest Transport (Covered) 	OPFOR 	CSAT (Pacific) 
				{
					cost = 250;
					requirements[] = {};
				};
				class O_T_APC_Wheeled_02_rcws_v2_ghex_F // MSE-3 Marid 	OPFOR 	CSAT (Pacific) 
				{
					cost = 3000;
					requirements[] = {};
				};
				class O_G_Offroad_01_repair_F // Offroad (Repair) 	OPFOR 	FIA  
				{
					cost = 500;
					requirements[] = {};
				};
				class O_G_Van_01_fuel_F // Fuel Truck 	OPFOR 	FIA 
				{
					cost = 750;
					requirements[] = {};
				};
				class O_G_Van_02_transport_F // Van Transport 	OPFOR 	FIA  
				{
					cost = 200;
					requirements[] = {};
				};
				class O_UGV_02_Demining_F // Akinaka ED-1D 	OPFOR 	CSAT 
				{
					cost = 750;
					requirements[] = {};
				};
				class O_T_UGV_01_rcws_ghex_F // UGV Saif RCWS 	OPFOR 	CSAT (Pacific
				{
					cost = 1000;
					requirements[] = {};
				};
			};
			class Aircraft
			{
				class O_UAV_01_F // Tayran AR-2 	OPFOR 	CSAT 
				{
					cost = 500;
					requirements[] = {};
				};
				class O_Heli_Light_02_F // PO-30 Orca 	OPFOR 	CSAT 
				{
					cost = 750;
					requirements[] = {H};
				};
			};
			class Naval
			{
				class O_Boat_Transport_01_F // Assault Boat 	OPFOR 	CSAT 
				{
					cost = 100;
					requirements[] = { "W" };
				};
			};
			class Gear
			{
				class Box_East_Wps_F // Basic Weapons [CSAT] 	Civilian 	Supplies 
				{ 
					cost = 250;
					requirements[] = {};
				};
				class Box_East_WpsSpecial_F // Special Weapons [CSAT] 	Civilian 	Supplies
				{
					cost = 500;
					requirements[] = {};
				};
				class Box_East_Ammo_F // Basic Ammo [CSAT] 	Civilian 	Supplies 
				{
					cost = 200;
					requirements[] = {};
				};
				class Box_East_AmmoOrd_F // Explosives [CSAT] 	Civilian 	Supplies 
				{
					cost = 250;
					requirements[] = {};
				};
				class Box_East_Grenades_F // Grenades [CSAT] 	Civilian 	Supplies  
				{
					cost = 200;
					requirements[] = {};
				};
				class Box_East_Support_F // Support [CSAT] 	Civilian 	Supplies 
				{
					cost = 200;
					requirements[] = {};
				};
				class Box_East_WpsLaunch_F // Launchers [CSAT] 	Civilian 	Supplies 
				{
					cost = 300;
					requirements[] = {};
				};
				class Box_East_AmmoVeh_F // Vehicle Ammo [CSAT] 	Civilian 	Supplies 
				{
					cost = 500;
					requirements[] = {};
				};
				class O_supplyCrate_F // Supply Box [CSAT] 	Civilian 	Supplies 
				{
					cost = 200;
					requirements[] = {};
				};
				class Land_RepairDepot_01_green_F // Repair depot (Green) 	Civilian 	Supplies 
				{
					cost = 1000;
					requirements[] = {};
				};
				
			};
			class Defences
			{
				class O_HMG_01_F // Mk30 HMG .50 	OPFOR 	CSA
				{
					cost = 250;
					requirements[] = {};
					offset[] = { 0, 5.3, 0 }; // --- custom offset (optional)
				};
				class O_HMG_01_high_F // Mk30 HMG .50 (Raised)
				{
					cost = 250;
					requirements[] = {};
					offset[] = { 0, 5.3, 0 }; // --- custom offset (optional)
				};
				class O_HMG_01_A_F // Mk30A HMG .50
				{
					cost = 500;
					requirements[] = {};
					offset[] = { 0, 5.3, 0 }; // --- custom offset (optional)
				};
				class O_GMG_01_F // Mk32 GMG 20 mm
				{
					cost = 250;
					requirements[] = {};
					offset[] = { 0, 5.3, 0 }; // --- custom offset (optional)
				};
				class O_GMG_01_high_F // Mk32 GMG 20 mm (Raised) 	OPFOR 	CSAT 
				{
					cost = 250;
					requirements[] = {};
					offset[] = { 0, 5.3, 0 }; // --- custom offset (optional)
				};
				class O_GMG_01_A_F // Mk32A GMG 20 mm 	OPFOR 	CSAT 
				{
					cost = 5000;
					requirements[] = {};
					offset[] = { 0, 5.3, 0 }; // --- custom offset (optional)
				};
				class O_static_AA_F // Static Titan Launcher (AA) [CSAT] 	OPFOR 	CSAT  
				{
					cost = 500;
					requirements[] = {};
					offset[] = { 0, 5.3, 0 }; // --- custom offset (optional)
				};
				class O_static_AT_F // Static Titan Launcher (AT) [CSAT] 	OPFOR 	CSAT 
				{
					cost = 500;
					requirements[] = {};
					offset[] = { 0, 5.3, 0 }; // --- custom offset (optional)
				};
			};
		};
	};
};

class CfgWLFactionAssets
{
	class INDEP // --- Independent
	{
		class InfantryGroups // --- independent faction uses group configs to spawn garrisons; you can define various group types to be randomly used
		{
			groups[] = {
				"'Indep' >> 'IND_E_F' >> 'Infantry' >> 'I_E_InfSquad'", // --- use this part of the config path found in the Config viewer (CfgGroups)
				"'Indep' >> 'IND_E_F' >> 'Infantry' >> 'I_E_InfTeam'" , // --- NOTE THE QUOTATION MARKS AND APOSTROPHES
				"'Indep' >> 'IND_G_F' >> 'Infantry' >> 'I_G_InfSquad_Assault'", //
			};
		};
		class MotorizedGroups
		{
			groups[] = {
			"'Indep' >> 'IND_E_F' >> 'Infantry' >> 'I_E_MotInf_Team'", //
				
			};
		};
		class MechanizedGroups
		{
			groups[] = {
			"'Indep' >> 'IND_E_F' >> 'Infantry' >> 'I_E_MechInfSquad'", //
				
			};
		};
		class ArmoredGroups
		{
			groups[] = {
				
			};
		};
	};
};

WLAIRequisitonBlacklist[] = {
	
};
	